schema_version: 1

context:
  name: sagemaker-code-editor
  version: "1.8.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - if: linux and x86_64
    then:
      url: https://github.com/aws/code-editor/releases/download/1.0.2/code-editor-sagemaker-server-1.0.2.tar.gz
      sha256: 400542d325df26865c53d6671f42e86f9d3c71d69dc20d8000a379d44c6999e3
      target_directory: vscode-reh-web-linux-x64

build:
  skip:
    - win
    - osx and x86_64
  number: 0
  dynamic_linking:
    binary_relocation: false

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
  host:
    - nodejs 20.*
  run:
    - nodejs 20.*

tests:
  - script:
    - set -x  
    - echo "Check CLI installed..."
    - ls -l ${PREFIX}/bin
    - test -f ${PREFIX}/bin/sagemaker-code-editor

    - echo "Check main script exist s..."
    - ls -l ${PREFIX}/share/sagemaker-code-editor/out
    - test -f ${PREFIX}/share/sagemaker-code-editor/out/server-main.js

    - echo "Check node present..."
    - node --version

    - echo "Check ripgrep binaries..."
    - $CONDA_PREFIX/share/sagemaker-code-editor/node_modules/@vscode/ripgrep/bin/rg --version

    - echo "Check sagemaker-code-editor binaries..."
    - sagemaker-code-editor --help

about:
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - LICENSE.vscode.txt
    - LICENSE-THIRD-PARTY
    - ThirdPartyNotices.vscode.txt
  summary: Code Editor based on Code-OSS, Visual Studio Code Open Source
  homepage: https://aws.amazon.com/sagemaker/
  repository: https://github.com/aws/sagemaker-code-editor/

extra:
  recipe-maintainers:
    - sgganjo
    - joshuatowner
    - edwardps
    - NewtonDer
    - aws-prayags
    - arkaprava08
